name: Run Playwright Test on Self-hosted Runner

on:
  workflow_dispatch:  # 僅允許手動觸發

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 如果你不需要檢出 Git 倉庫，可以移除這一段
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      shell: cmd
      run: npm install

    - name: Install Playwright browsers
      shell: cmd
      run: npx playwright install --with-deps

    - name: Run specific Playwright test - Rectangle
      shell: cmd
      run: npx playwright test Rectangle.spec.js

    - name: Run specific Playwright test - Galaxsys
      shell: cmd
      run: npx playwright test galaxsys.spec.js

    - name: Run specific Playwright test - Wcasino
      shell: cmd
      run: npx playwright test Wcasino.spec.js