name: Run Playwright Test on Self-hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 確保你的 Runner 標籤符合

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies with Bypass
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
        npm install

    - name: Install Playwright browsers with Bypass
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
        npx playwright install --with-deps

    - name: Run specific Playwright test with Bypass
      shell: powershell
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
        npx playwright test Playson.spec.js