name: Run Playwright Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # 根據需要調整 Node 版本

    - name: Install dependencies
      run: npm install

    - name: Run specific Playwright test
      run: npx playwright test Playson.spec.js