name: Run Playwright Test on Self-hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 或 Windows runner 標籤

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 設定 PowerShell 執行政策
    - name: Set PowerShell Execution Policy to Bypass
      shell: pwsh
      run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run specific Playwright test
      run: npx playwright test Playson.spec.js