name: Run Playwright Test on Self-hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 請確保你的自架設 Runner 標籤符合

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      shell: cmd
      run: npm install

    - name: Install Playwright browsers
      shell: cmd
      run: npx playwright install --with-deps

    - name: Run specific Playwright test
      shell: cmd
      run: npx playwright test Rectangle.spec.js