name: Run Playwright Test on Self-hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # 若你希望以 polyfill 確保 global.performance 定義，
    # 可選擇下列步驟（此處以 CMD shell 生成檔案，然後在測試前執行）
    - name: Create performance polyfill script
      shell: cmd
      run: echo global.performance = require('perf_hooks').performance; > setup-performance.js

    - name: Install dependencies
      shell: cmd
      run: npm install

    - name: Install Playwright browsers
      shell: cmd
      run: npx playwright install --with-deps

    - name: Run specific Playwright test
      shell: cmd
      run: node setup-performance.js && npx playwright test Playson.spec.js