name: Run Playwright Test on Self-hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set Execution Policy to Bypass (using pwsh)
      shell: pwsh
      run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run specific Playwright test
      run: npx playwright test Playson.spec.js